手撕Attention 参考（https://blog.csdn.net/wl1780852311/article/details/120981553）

Numpy 版本

In [2]:
import numpy as np
from numpy.random import randn

创造一个 256 * 32 的矩阵X
randn会返回一个或者一组样本，具有标准正态分布
例子：
np.random.randn() # 没有参数时，会返回单个数据
如果有参数那就会返回 高宽，（2,4）就是 高2宽4，（4,3,2)就是 高4 高 3 宽2

In [3]:
d = 256 # dimension
n = 32 # 32 个序列
x = randn(d,n)
x.shape

(256, 32)

attention最重要的三个向量
q : queue
k : key
v : value

In [4]:
w_q = randn(d,d) # 256 * 256 的正态分布矩阵
w_k = randn(d,d) # 256 * 256 的正态分布矩阵
w_v = randn(d,d) # 256 * 256 的正态分布矩阵

q = w_q @ x # @ 是执行矩阵和矩阵之间的乘法 这样就会的到向量q
k = w_k @ x # @ 是执行矩阵和矩阵之间的乘法 这样就会的到向量k
v = w_v @ x # @ 是执行矩阵和矩阵之间的乘法 这样就会的到向量v

q.shape

(256, 32)

In [6]:
A = k.T @ q # k.T 就是把k翻转
A.shape,v.shape

((32, 32), (256, 32))

In [7]:
A /= np.sqrt(d)
A

array([[-186.28152546, -327.31091177,  901.78046071, ..., -685.52216777,
         140.49093616,  -18.59303539],
       [ 215.02701858,  222.46104928, -129.31239471, ...,   51.208476  ,
        -337.49968243,  -78.86530934],
       [ 295.10610265, -133.33272948, -298.71067818, ..., -335.54932857,
         249.05942478,  116.71229805],
       ...,
       [-120.38985538, -396.0853944 ,   79.99435585, ...,   22.17684716,
           2.65507161, -235.80163013],
       [ 243.77606635, -180.82252053,  169.29970995, ..., -592.71327039,
         -55.77713235,  112.95361433],
       [-409.84986147,   90.78628911,  192.07422874, ...,  138.23986669,
        -175.57984414,   90.64594738]])

In [ ]:
def softmax(x):
    e_x = np.exp(x-np.max(x)) #防溢出
    return e_x/e_x.sum(axis = 0)

In [8]:
A_hat = softmax(A)
A_hat

array([[0.00000000e+000, 0.00000000e+000, 1.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [3.77552573e-060, 6.39051626e-057, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [1.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 1.00503663e-020, 0.00000000e+000],
       ...,
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [3.01783888e-117, 0.00000000e+000, 1.36466332e-149, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.25736337e-231, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [11]:
output = v @ A_hat
output

array([[-2.82020593e+01,  1.45791903e-23,  2.68626059e+01, ...,
         9.85585373e-01, -3.12174858e+01, -3.72031252e-58],
       [-6.42106743e+01, -8.10166305e-26,  2.82501107e+00, ...,
         5.08977665e+01,  1.17836465e+01,  9.69096388e-59],
       [-3.06145712e+01,  8.77560561e-24,  1.35399065e+01, ...,
        -1.80679906e+01, -2.42719966e+01, -7.33615321e-58],
       ...,
       [-4.48008010e+01,  2.73512020e-23,  2.60210698e+01, ...,
        -2.45475909e+01, -1.22014549e+01, -2.90356097e-58],
       [-1.33037716e+01, -1.70305455e-24, -1.61389014e+01, ...,
         1.76756471e+00, -2.44616246e+01,  2.43349465e-58],
       [ 1.29454598e+01, -3.74118583e-23, -3.17166235e+01, ...,
        -1.18961325e+01,  2.39138807e+01,  6.39741731e-59]])

In [12]:
output.shape

(256, 32)